# Generated by Django 5.1.4 on 2024-12-19 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome')),
                ('vagas', models.IntegerField(verbose_name='Vagas')),
                ('periodos', models.IntegerField(verbose_name='Perídos')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome')),
                ('periodo_atual', models.IntegerField(verbose_name='Perído Atual')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome')),
                ('periodo_requerido', models.IntegerField(verbose_name='Perído Requerido')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Valor')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.disciplina')),
            ],
        ),
    ]
